"""Added OAuth back

Revision ID: 3d366b48929e
Revises: 2657b80a2c69
Create Date: 2023-07-22 21:36:23.007073

"""
import fastapi_users_db_sqlalchemy

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d366b48929e'
down_revision = '2657b80a2c69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_account',
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column(
                        'id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column('oauth_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('access_token', sa.String(
                        length=1024), nullable=False),
                    sa.Column('expires_at', sa.Integer(), nullable=True),
                    sa.Column('refresh_token', sa.String(
                        length=1024), nullable=True),
                    sa.Column('account_id', sa.String(
                        length=320), nullable=False),
                    sa.Column('account_email', sa.String(
                        length=320), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_oauth_account_account_id'),
                    'oauth_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_account_oauth_name'),
                    'oauth_account', ['oauth_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_account_oauth_name'),
                  table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'),
                  table_name='oauth_account')
    op.drop_table('oauth_account')
    # ### end Alembic commands ###
