"""Fixed many-to-many relationship with Member and Role models

Revision ID: 7419494187b7
Revises: 0216f14cf028
Create Date: 2023-07-22 20:55:15.174995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7419494187b7'
down_revision = '0216f14cf028'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
