version: "3"

services:
  user_database:
    container_name: user_database
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "5433:5432"
    env_file:
      - ./jutsu-services/auth-service/.env

  user_token_database:
    container_name: user_token_database
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    ports:
      - "6379:6379"
    env_file:
      - ./jutsu-services/auth-service/.env
  
  auth_service:
    container_name: auth_service
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./jutsu-services/auth-service:/app
    restart: on-failure
    env_file:
      - ./jutsu-services/auth-service/.env
    command: ["./scripts/startup.sh"]
