version: "3"

services:
  user_database:
    container_name: user_database
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    ports:
      - "5433:5432"
    env_file:
      - ./jutsu-services/auth-service/.env

  project_database:
    container_name: project_database
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - ./jutsu-services/project-service/.env

  user_token_database:
    container_name: user_token_database
    build:
      context: .
      dockerfile: containers/redis/Dockerfile
    ports:
      - "6379:6379"
    env_file:
      - ./jutsu-services/auth-service/.env

  auth_service:
    container_name: auth_service
    build:
      context: .
      dockerfile: containers/auth-service/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./jutsu-services/auth-service:/app
    restart: on-failure
    env_file:
      - ./jutsu-services/auth-service/.env
    command: ["./scripts/startup.sh"]

  project_service:
    container_name: project_service
    build:
      context: .
      dockerfile: containers/project-service/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./jutsu-services/project-service:/app
    restart: on-failure
    env_file:
      - ./jutsu-services/project-service/.env
    command: ["./scripts/startup.sh"]

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  kong:
    container_name: kong_gateway
    build:
      context: .
      dockerfile: containers/kong/Dockerfile
    ports:
      - "9000:8000" # Proxy port
      - "8443:8443" # Proxy SSL port
      - "9001:8001" # Admin API port
