"""Using one name field instead of two seperate first- and lastname fields

Revision ID: 0a78ee57e1a5
Revises: 659926c51e0a
Create Date: 2023-09-24 21:49:31.324886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a78ee57e1a5'
down_revision = '659926c51e0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('members', 'first_name')
    op.drop_column('members', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('members', 'name')
    # ### end Alembic commands ###
