"""first_name and last_name of Member are made optional

Revision ID: bc8b59d2078a
Revises: 3d366b48929e
Create Date: 2023-09-10 20:12:03.268126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8b59d2078a'
down_revision = '3d366b48929e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
