"""Rename Team to Clan

Revision ID: e298036d788e
Revises: bc8b59d2078a
Create Date: 2023-09-22 13:11:59.274785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e298036d788e'
down_revision = 'bc8b59d2078a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clans_name'), 'clans', ['name'], unique=True)
    op.create_table('clan_members',
    sa.Column('clan_id', sa.UUID(), nullable=True),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], )
    )
    op.drop_table('team_members')
    op.drop_index('ix_teams_name', table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='teams_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='teams_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_teams_name', 'teams', ['name'], unique=False)
    op.create_table('team_members',
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name='team_members_member_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='team_members_team_id_fkey')
    )
    op.drop_table('clan_members')
    op.drop_index(op.f('ix_clans_name'), table_name='clans')
    op.drop_table('clans')
    # ### end Alembic commands ###
