name: Docker Build and Push

on:
  push:
    branches: [master]
    paths:
      - "docker/python/Dockerfile"
      - "docker/postgres/Dockerfile"
      - "docker/redis/Dockerfile"
  pull_request:
    branches: [master]
    paths:
      - "docker/python/Dockerfile"
      - "docker/postgres/Dockerfile"
      - "docker/redis/Dockerfile"

jobs:
  docker-python:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        name: Build an image from checkout

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and push Python Docker image
        with:
          image: jutsuteck/pyjutsu-base
          tags: latest
          registry: docker.io
          dockerfile: ./docker/python/Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  docker-postgres:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and push PostgreSQL Docker image
        with:
          image: jutsuteck/jutsu-postgres-base
          tags: latest
          registry: docker.io
          dockerfile: ./docker/postgres/Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  docker-redis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and push Redis Docker image
        with:
          image: jutsuteck/jutsu-redis-base
          tags: latest
          registry: docker.io
          dockerfile: ./docker/redis/Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
