version: "3"

services:
  user_database:
    container_name: user_database
    build:
      context: ./auth-service
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "5433:5432"
    env_file:
      - ./auth-service/.env

  user_token_database:
    container_name: user_token_database
    build:
      context: ./auth-service
      dockerfile: docker/redis/Dockerfile
    ports:
      - "6379:6379"
    env_file:
      - ./auth-service/.env
  
  auth_service:
    container_name: auth_service
    build:
      context: ./auth-service
      dockerfile: docker/app/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./auth-service:/app
    restart: on-failure
    env_file:
      - ./auth-service/.env
